apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromc
  labels:
    app: vpromc
spec:
  selector:
    matchLabels:
      app: vpromc
  template:
    metadata:
      labels:
        app: vpromc
    spec:
      containers:
        - name: memcache
          image: memcached
          ports:
            - name: vpromc-port
              containerPort: 11211
              protocol: TCP
      restartPolicy: Always
      